server {
      listen 8889;
      server_name 118.31.165.121;

      # 前端静态文件
      location / {
          root /work/task_manage/h5_app/;
          index index.html;
          try_files $uri $uri/ /index.html;
	  # 解决跨域（可选）
          add_header Access-Control-Allow-Origin *;	
      }

      # 后端 API 反向代理
      location /api/ {
          proxy_pass http://118.31.165.121:9090/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

     location /resource/ {
        root   /work/task_manage/; # 拼接后：/work/task_manage/resource/
        autoindex off;
        expires 30d;
        add_header Access-Control-Allow-Origin *;
    }

    location = /favicon.ico {
        root   /work/task_manage/h5_app;
        expires 30d;
    }
  }
